name: Update Motivational Quote

on:
  schedule:
    - cron: '0 */2 * * *' # Runs every 2 hours
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Read motivational quotes
      id: read-quotes
      run: |
        echo "Reading motivational quotes from motivational_quotes.txt..."
        QUOTES=($(cat motivational_quotes.txt))
        INDEX=$((RANDOM % ${#QUOTES[@]}))
        SELECTED_QUOTE=${QUOTES[$INDEX]}
        echo "::set-output name=quote::$SELECTED_QUOTE"

    - name: Update README.md
      run: |
        echo "Updating README.md with the new motivational quote..."
        sed -i "/✨ Motivational Quote:/c\ Motivational Quote: ${{ steps.read-quotes.outputs.quote }}" README.md

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add README.md
        git commit -m "Update motivational quote"
        git push
